apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-mariadb-on-k8s-mariadb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/Git/grafana_mariadb_on_k8s/mariadb-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-mariadb-on-k8s-mariadb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi