apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-mariadb-on-k8s-prometheus-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/Git/grafana_mariadb_on_k8s/prometheus-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-mariadb-on-k8s-prometheus-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
