apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-mariadb-on-k8s-prometheus-config
  labels:
    app: grafana-mariadb-on-k8s-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # How frequently to scrape targets
      evaluation_interval: 15s # How frequently to evaluate rules

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090'] # Prometheus scrapes itself

      - job_name: 'mariadb'
        static_configs:
          - targets: ['grafana-mariadb-on-k8s-mariadb-service:9104'] # Scrape MariaDB Exporter
